---
title: "Task1"
author: "Mihir"
date: "03/11/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warnings = FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(rio)
library(knitr)
library(readxl)
library(lubridate)
library(caret)
library(stringr)
#library(e1071)
```

```{r data manipulations, warnings = FALSE, message = FALSE}
#Import

albumdatgen <- function(){
  maindat <- read_excel("edited_spotify.xlsx")

  #NA Removal
  maindat <- na.omit({ 
    maindat %>%
      group_by(Artist, AlbumName, AlbumReleaseDate, ArtistPopularity)
  })

  #Date Parsing
  maindat$AlbumReleaseDate = as.Date(parse_date_time(
    maindat$AlbumReleaseDate, orders = c("y", "ym", "ymd")))

  #Grouping data by albums because there is no data to calculate an individual       track's popularity.
  albumdat = {maindat %>% 
      group_by(Artist,ArtistPopularity,AlbumName,
               AlbumReleaseDate,AlbumPopularity,ArtistNumFollowers,
               AlbumWeeksOnChart,AlbumWeeksNumberOne,
               AlbumBestChartPosition) %>% 
      summarise(AlbumDuration = mean(TrackDuration),
                AlbumDanceability = mean(TrackDanceability),
                AlbumEnergy = mean(TrackEnergy),
                AlbumLoudness = mean(TrackLoudness),
                AlbumSpeechiness = mean(TrackSpeechiness),
                AlbumAcousticness = mean(TrackAcousticness),
                AlbumInstrumentalness = mean(TrackInstrumentalness),
                AlbumLiveness = mean(TrackLiveness),
                AlbumValence = mean(TrackValence),
                AlbumTempo = mean(TrackTempo)
                 )}

  #Calculating the AlbumPopularityRating and ReleaseYear for each album.
  albumdat <- {albumdat %>% 
    group_by(Artist, AlbumName, AlbumReleaseDate) %>%
      mutate(AlbumPopularityRating = 
                ((ArtistPopularity + AlbumPopularity)/2) +
                floor((ArtistNumFollowers/10^6)) +
                (AlbumWeeksOnChart/100) +
                (AlbumWeeksNumberOne/10) +
                (1 - (AlbumBestChartPosition/100)),
             ReleaseYear = year(AlbumReleaseDate))
  }
  albumdat[10:19] <- normalise(albumdat[10:19])
  return(albumdat)
}

#ArtistPopularityRating is an average of all AlbumPopularityRatings for that artist.
#artistdat <- {albumdat %>% 
 #   group_by(Artist) %>%
  #  summarise(ArtistPopularityRating = mean(AlbumPopularityRating))}

#Training data set generator.
trainsetgen <- function(test_data, data, year){
    
  #Training data excludes the entries from test_data
  train_data <- anti_join(data, test_data, by = c("Artist", "AlbumName"))
  if(year <= 1964){
    return(filter(train_data, (ReleaseYear <= 1964)))
  }
  else if(year > 1964 & year <= 1975){
    return(filter(train_data, (ReleaseYear > 1964), (ReleaseYear <= 1975)))
  }
  else if(year > 1975 & year <= 1992){
      return(filter(train_data, (ReleaseYear > 1975), (ReleaseYear <= 1992)))
  }
  else if(year > 1992 & year <= 2002){
      return(filter(train_data, (ReleaseYear > 1992), (ReleaseYear <= 2002)))
  }
  else if(year > 2002){
    return(filter(train_data, (ReleaseYear > 2002)))
  }
}

#Testing data set generator.
testsetgen <- function(){
  intrain <- createDataPartition(y = albumdat$AlbumPopularityRating, 
                                 p= 0.05, list = FALSE)
  return(albumdat[intrain,])
}

```

```{r txt to df parser, warnings = FALSE, message = FALSE}
fetch_test <- function(filename){
  # e.g. filename = test_albums_2.txt
  source <- paste("test_albums",filename, sep = "/")
  TData <- read.table(source)

  test_data <- matrix(ncol = 2)

  #Word selects all phrases between the commas
  for (i in (1:dim(TData)[1])) {
    test_data <-
      rbind(test_data, c(word(TData[i, 1], 1:2, sep = fixed(': '))))
  }

  test_data <- test_data[-1, ]
  test_data <- as_tibble(test_data)
  colnames(test_data) <- c("Artist", "AlbumName")
  
  test_data <- filter(albumdat, (Artist %in% as.list(test_data$Artist)) &
                       (AlbumName %in% as.list(test_data$AlbumName)))
  
  return(test_data)
}

```

```{r knn algorithm, warnings = FALSE, message = FALSE}
run_knn <- function(test_data, artistname, album){
  entry <- filter(albumdat, (Artist == artistname)&(AlbumName == album))
  year <- entry$ReleaseYear
  training_set <- trainsetgen(test_data, albumdat, year)
  
  #To control the nuances of our model training function, we set the resampling      method to repeated cross-validation with 10 resampling iterations and 3          complete sets of folds to compute for our repeated cross-validation
  trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)
  
  pred1 <- train(AlbumPopularityRating ~ AlbumDanceability + 
                          AlbumEnergy + AlbumLiveness + 
                          AlbumValence, data = training_set, 
                        method = "knn", trControl=trctrl, 
                        preProcess = c("center", "scale"), tuneLength = 10)

  pred2 <- train(AlbumPopularityRating ~  AlbumAcousticness +
                          AlbumInstrumentalness, data = training_set, 
                        method = "knn", trControl=trctrl, 
                        preProcess = c("center", "scale"), tuneLength = 10)

  pred3 <- train(AlbumPopularityRating ~ AlbumSpeechiness + 
                        AlbumDuration, data = training_set, 
                        method = "knn", trControl=trctrl, 
                        preProcess = c("center", "scale"), tuneLength = 10)
 
  poppred1 <-  predict(pred1, newdata = entry)
  poppred2 <-  predict(pred2, newdata = entry)
  poppred3 <-  predict(pred3, newdata = entry)
  
  poppred <- mean(poppred1, poppred2, poppred3)
  entry <- {entry %>% group_by(Artist, AlbumName) %>%
      mutate(PopularityPrediction = poppred)}
  
  return(entry$PopularityPrediction)
}
```

```{r predictor, warnings = FALSE, message = FALSE}
predict_popularity <- function(filename){
  test_data <- fetch_test(filename)
  
  test_data <- test_data %>% group_by(Artist, AlbumName) %>%
    mutate(PredictedPopularity = run_knn(test_data, Artist, AlbumName)) %>%
    mutate(AbsolutePercentageError = 
             (abs(PredictedPopularity - AlbumPopularityRating)/
                AlbumPopularityRating)*100)

  print("The Mean Absolute % Error is: ")
  View(test_data)
  return(sum(test_data$AbsolutePercentageError)/length(test_data))
}

```

```{r test chunk, warnings = FALSE, message = FALSE}
albumdat <- albumdatgen()
test_set <- "test_albums_1.txt"
predict_popularity(test_set)
```

```{r normalise, warnings = FALSE, message = FALSE}
normalise <- function(dat){
  for(i in 1:ncol(dat)){
    dat[i] <- (dat[i] - min(dat[i])) / (max(dat[i]) - min(dat[i]))
  }
  return(dat)
}
```

```{r PCA, warnings = FALSE, message = FALSE}

# Retrieve and normalise data
pca_dat <- albumdatgen()
pca_dat[10:19] <- normalise(pca_dat[10:19])
#summary(pca_dat)

# Finding the principal components
pca <- princomp(pca_dat[10:19],cor="FALSE")

pc <- pca$scores

summary(pca)

biplot(pca)

screeplot(pca, type="lines")
```

---

```{r EDA, include = FALSE}
plot.durationpop <- {albumdat %>% ggplot(aes(x = AlbumDuration,
                                                y = PopularityRating))} +
  geom_point()  + geom_smooth() + xlab("Album's Average Duration") +
        ylab("Album's Popularity Rating") +
        ggtitle("Duration vs Popularity")
plot.durationpop

plot.dancepop <- {albumdat %>% ggplot(aes(y = AlbumDanceability,
                                                x = PopularityRating))} +
  geom_point()  + geom_smooth() + ylab("Album's Average Danceability") +
        xlab("Album's Popularity Rating") +
        ggtitle("Popularity vs Danceability")
plot.dancepop

plot.energypop <- {albumdat %>% ggplot(aes(y = AlbumEnergy,
                                                x = PopularityRating))} +
  geom_point()  + geom_smooth() + ylab("Album's Average Energy") +
        xlab("Album's Popularity Rating") +
        ggtitle("Popularity vs AlbumEnergy")
plot.energypop

plot.speechypop <- {albumdat %>% ggplot(aes(y = AlbumSpeechiness,
                                                x = PopularityRating))} +
  geom_point()  + geom_smooth() + ylab("Album's Average Speechiness") +
        xlab("Album's Popularity Rating") +
        ggtitle("Popularity vs Speechiness")
plot.speechypop


```

---