---
title: "Group Task 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import}
library(readxl)
Spotify <- read_excel("edited_spotify.xlsx")
test <- read_excel("test_track.xlsx")
```


```{r retrieve useful data}
df <- data.frame(Spotify)
cols <- c(1,3,6,13,17:27)
df <- df[,cols]
```


find min, max, 10% range (score 1-10)
```{r define function}
assignscore <- function(varname, test, df){
  valuelist = df[varname]
  min1 = min(valuelist)
  max1 = max(valuelist)
  testinput = unlist(lapply(test[varname], "[[", 1))
  len = length(valuelist)
  for (i in (1:len)){
    valuelist[i] <- 10 - floor(abs(valuelist[i]-testinput)/((max1-min1)/10))
  }
  return(valuelist)
  #df[varname] <- valuelist
}

```


```{r separate var for later treatments}
varlist_cat <- list('Artist','AlbumName')
varlist_score <- colnames(df)[5:15]
to_do <- 'ArtistGenres'
```


```{r check for basic info}
test_artist = unlist(lapply(test['Artist'], "[[", 1))
test_album = unlist(lapply(test['AlbumName'], "[[", 1))
for (i in (1:length(df['TrackName']))){
  df['Artist'][i] <- ifelse(df['Artist'][i] == test_artist, 10, 0)
  df['AlbumName'][i] <- ifelse(df['AlbumName'][i] == test_album, 10, 0)
}
```


```{r loop through character vars}
for (var in varlist){
  valuelist <- assignscore(var, test, df)
  df[var] <- valuelist
}
```


```{r}
library(dplyr)
df_total_score <-df %>% mutate(Total = select(., c(Artist, AlbumName, TrackDanceability:TrackTempo)) %>% rowSums(na.rm = TRUE))
```

get the second highest mark -- highest is the input
```{r}
df_total_score <- df_total_score[-which.max(df_total_score$Total), ]
first <- df_total_score[which.max(df_total_score$Total), ]
output_track <- unlist(lapply(first['TrackName'], "[[", 1))
output_track
```